name: "Lint"

on:
  push:
  schedule:
    - cron: "0 18 * * 0"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.1.0
        with:
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: true
          use-mypy: false
          use-isort: false
          extra-flake8-options: --max-line-length 88 --ignore E203,W503
