name: "Lint"

on:
  push:
  schedule:
    - cron: "0 18 * * 0"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Black
        run: black .